__author__ = 'julian'
''' Based on an idea generated by reading : http://answers.oreilly.com/topic/1198-an-introduction-to-genetic-algorithms-in-python/
Genetic Sort
'''

class geneticdata(list):
    def __init__():
        pass

    def fitness(self):
        pass


def mutation():
    pass

def swap():
    pass

def


if __name__ == "__main__":
    import doctest
    doctest.testmod()

print ("Start genetic sort")
g= [3,6,7,2,4,1,55,22,11]
geneticsort(g)

  